/* =========================================================================
   dither.js — Bayer ordered dither with a drifting threshold, applied to the
   scene and revealed only on the approach into the frame.

   WHAT THE EFFECT ACTUALLY IS
   Modelled on the Outsource Consulting header. Two parts:

     the dotty    an 8x8 Bayer ordered dither, hard-thresholded to exactly
                  two colours: mix(dark, light, step(threshold, luminance)).
                  Not a halftone of round dots — an ordered dither, whose
                  cell is a pixel or two across. That is what makes it read
                  as micro-fine texture rather than as printed dots.

     the wave     the dither THRESHOLD is biased by 3D noise drifting in
                  time, plus a slow global pulse. Because the threshold
                  moves, the boundary between the two colours migrates, and
                  broad bands appear to flow through the image. The dots
                  themselves never move; only the level at which each one
                  flips. That is the whole trick.

   WHERE IT LIVES
   On the scene's own materials, not on a canvas overlay. The frame is real
   geometry at z ~ 0 and the cloud, water and sky sit near z = -170, so what
   reads as "the picture in the frame" is the far scene seen through the
   aperture. Screening the materials lets the wall and frame occlude the
   effect for free. An overlay has no depth and would paint the wall, the
   frame and the captions too.

   WHEN IT APPEARS
   Only on the second scroll — the move that carries the camera into the
   frame. Phase 1 and phase 2 are left completely clean.

       t = 0.0   phase 1                     amount 0
       t = 0.5   phase 2, camera pulled back amount 0
       t = 1.0   phase 3, into the frame     amount 1

   BAYER WITHOUT A LOOKUP TABLE
   The reference declares `const float bayerMatrix8x8[64]`, which is GLSL ES
   3.00 syntax. The materials patched here compile as GLSL ES 1.00, where
   that array constructor is invalid, so the matrix is generated by the
   standard recursive identity instead — same values, no table.
   ========================================================================= */

(function () {
  'use strict';

  const hex = h => [parseInt(h.slice(1, 3), 16) / 255,
                    parseInt(h.slice(3, 5), 16) / 255,
                    parseInt(h.slice(5, 7), 16) / 255];

  // Values taken from the reference implementation's own uniform defaults.
  //
  // The single thing that makes it read as SOFT is the colour pair: the light
  // end is rgb(183,185,211), a pale lavender-grey, NOT a white. Against
  // #1925aa that is a low-contrast couple, so the two-tone dither stays
  // atmospheric. Mapping the light end to mercury (#e8e6e0) instead roughly
  // triples the contrast and the picture snaps into harsh posterised blocks —
  // which is exactly what went wrong before.
  const CFG = {
    dark:  hex('#1925aa'),   // OCI blue
    light: hex('#b7b9d3'),   // pale lavender-grey, per the reference
    scale: 1.0,              // device px per Bayer cell — the reference's finest
    bias: 0.10,
    noiseScale: 1.4,         // broad, low-frequency field across the screen
    noiseSpeed: 1.2,         // the reference runs 94 here, which is effectively
                             // per-frame flicker; a slow drift reads better on
                             // a moving 3D scene than on a still photograph
    noiseWeight: 0.77,
    pulseSpeed: 3.1,
    pulseWeight: 0.87,
    strength: 0.29,          // overall reach of the animated bias
    // The reference runs uDitherAmount at 1, but it screens a flat photograph.
    // Here the screen sits over a lit 3D scene, and taking it all the way
    // throws away the cloud's modelling and the water's gradient. Holding a
    // little of the original underneath keeps the picture readable and the
    // texture atmospheric rather than graphic.
    maxAmount: 0.68,
    start: 0.5,              // ramp begins here: the second scroll
  };

  const GLSL = `
uniform float uDitherAmount;
uniform float uDitherScale;
uniform float uDitherTime;
uniform vec2  uDitherRes;
uniform vec3  uDitherDark;
uniform vec3  uDitherLight;
uniform vec4  uDitherNoise;   // scale, speed, weight, strength
uniform vec3  uDitherPulse;   // speed, weight, bias

// Bayer 8x8 by the recursive identity — GLSL ES 1.00 has no const array
// constructors, and this needs no uniform upload either.
float dwBayer2(vec2 a){ a = floor(a); return fract(a.x * 0.5 + a.y * a.y * 0.75); }
float dwBayer4(vec2 a){ return dwBayer2(0.5 * a) * 0.25 + dwBayer2(a); }
float dwBayer8(vec2 a){ return dwBayer4(0.5 * a) * 0.25 + dwBayer2(a); }

// The wave, as three travelling sine bands.
//
// The reference uses classic Perlin noise here. That is unaffordable in this
// scene: the water is a PlaneGeometry(300,300,1024,1024) — 2.1M triangles,
// most of them smaller than a pixel, so every one still shades a full 2x2
// quad. A value-noise field (8 hashes + 7 mixes) across ~8M fragment
// invocations dropped the scene to roughly 0.3fps. Three sines cost about a
// tenth of that and, for a slow drifting band, are visually indistinguishable.
float dwWave(vec2 p, float t){
  return sin(p.x * 1.7 + t * 0.90) * 0.50
       + sin(p.y * 2.3 - t * 0.70) * 0.32
       + sin((p.x + p.y) * 1.1 + t * 0.45) * 0.18;
}

vec3 dwDither(vec3 col){
  if (uDitherAmount <= 0.001) return col;

  float lum = dot(col, vec3(0.2126, 0.7152, 0.0722));

  // the wave: a drifting field plus a slow global pulse, both pushing the
  // threshold rather than the image
  // the field is in NORMALISED screen space, so its scale is independent of
  // resolution and of the Bayer cell size
  vec2 suv = gl_FragCoord.xy / max(uDitherRes, vec2(1.0));
  float n = dwWave(suv * uDitherNoise.x, uDitherTime * uDitherNoise.y);
  float pulse = sin(uDitherTime * uDitherPulse.x) * 0.5 + 0.5;
  float bias = uDitherPulse.z
             + (n * uDitherNoise.z + pulse * uDitherPulse.y) * uDitherNoise.w;

  float threshold = dwBayer8(gl_FragCoord.xy / uDitherScale) + bias;
  vec3 screened = mix(uDitherDark, uDitherLight, step(threshold, lum));

  return mix(col, screened, uDitherAmount);
}
`;

  // one uniform object shared by every patched material: a single write per
  // frame updates them all
  const U = {
    uDitherAmount: { value: 0 },
    uDitherScale:  { value: CFG.scale },
    uDitherTime:   { value: 0 },
    uDitherRes:    { value: [1, 1] },
    uDitherDark:   { value: CFG.dark },
    uDitherLight:  { value: CFG.light },
    uDitherNoise:  { value: [CFG.noiseScale, CFG.noiseSpeed,
                             CFG.noiseWeight, CFG.strength] },
    uDitherPulse:  { value: [CFG.pulseSpeed, CFG.pulseWeight, CFG.bias] },
  };

  function inject(src) {
    // Which output variable exists depends on the GLSL version this material
    // compiled to: ShaderMaterial defaults to ES 1.00 (gl_FragColor), three's
    // built-ins may come out as ES 3.00 (pc_fragColor).
    const out = src.includes('gl_FragColor') ? 'gl_FragColor'
              : src.includes('pc_fragColor') ? 'pc_fragColor'
              : null;
    if (!out) return null;
    const close = src.lastIndexOf('}');          // closes main()
    if (close < 0) return null;
    return GLSL + src.slice(0, close)
         + `\n  ${out}.rgb = dwDither(${out}.rgb);\n`
         + src.slice(close);
  }

  const patched = new WeakSet();
  let count = 0;

  function patchMaterial(m) {
    if (!m || patched.has(m)) return;
    patched.add(m);
    const prev = m.onBeforeCompile;
    m.onBeforeCompile = function (shader, renderer) {
      if (typeof prev === 'function') prev.call(this, shader, renderer);
      const next = inject(shader.fragmentShader);
      if (!next) return;
      shader.fragmentShader = next;
      Object.assign(shader.uniforms, U);
    };
    m.needsUpdate = true;
    count++;
  }

  // Walk the scene but never descend into anything tagged noHalftone — that
  // is the wall/frame model, tagged by recolor_hero.py. Excluding by mesh
  // name would be fragile: the glb carries meshes beyond the four the scene
  // names, and any unnamed one would get screened along with the artwork.
  function walk(obj) {
    if (!obj || (obj.userData && obj.userData.noHalftone)) return;
    if (obj.material) {
      if (Array.isArray(obj.material)) obj.material.forEach(patchMaterial);
      else patchMaterial(obj.material);
    }
    const kids = obj.children;
    if (kids) for (let i = 0; i < kids.length; i++) walk(kids[i]);
  }

  const clamp01 = v => Math.min(1, Math.max(0, v));
  const smooth = (e0, e1, x) => {
    const t = clamp01((x - e0) / (e1 - e0));
    return t * t * (3 - 2 * t);
  };

  let amount = 0, override = null, t0 = performance.now();

  function progress() {
    const cam = window.__dwCam, range = window.__dwRange;
    if (!cam || !range) return 0;
    const [gc, vw] = range;
    if (Math.abs(vw - gc) < 1e-6) return 0;
    return clamp01((cam.position.z - gc) / (vw - gc));
  }

  function start() {
    const scene = window.__dwScene;
    if (!scene) return setTimeout(start, 150);

    // The frame's museum label — "Wonderful Achievement (2024) / Giacomo
    // Merri" — is baked into the glb as three meshes: the card and its two
    // text lines. It belongs to Deep White's fiction, not this site, so it
    // is hidden whenever it appears.
    const PLAQUE = new Set(['label', 'Text', 'Text001']);
    function hidePlaque(root) {
      root.traverse(o => { if (o.isMesh && PLAQUE.has(o.name)) o.visible = false; });
    }

    walk(scene);
    hidePlaque(scene);
    // the glb arrives asynchronously and may bring more meshes; re-walk for a
    // while. patchMaterial is idempotent, so repeats cost nothing.
    let n = 0;
    const rescan = setInterval(() => {
      walk(scene);
      hidePlaque(scene);
      if (++n > 40) clearInterval(rescan);
    }, 250);

    (function tick(now) {
      const t = override !== null ? override : progress();
      // nothing at all until the second scroll begins
      amount += ((smooth(CFG.start, 1.0, t) * CFG.maxAmount) - amount) * 0.08;
      U.uDitherAmount.value = amount;
      U.uDitherTime.value = ((now || performance.now()) - t0) * 0.001;
      const r = window.__dwRenderer;
      if (r) {
        const dpr = r.getPixelRatio ? r.getPixelRatio() : 1;
        U.uDitherRes.value[0] = innerWidth * dpr;
        U.uDitherRes.value[1] = innerHeight * dpr;
      }
      requestAnimationFrame(tick);
    })();

    window.__dither = {
      get amount() { return amount; },
      get materials() { return count; },
      set: v => { override = v === null ? null : clamp01(v); },
      config: CFG,
      // live tuning: __dither.tune({scale: 3, noiseSpeed: 0.3})
      tune(o) {
        Object.assign(CFG, o);
        U.uDitherScale.value = CFG.scale;
        U.uDitherDark.value = CFG.dark;
        U.uDitherLight.value = CFG.light;
        U.uDitherNoise.value = [CFG.noiseScale, CFG.noiseSpeed,
                                CFG.noiseWeight, CFG.strength];
        U.uDitherPulse.value = [CFG.pulseSpeed, CFG.pulseWeight, CFG.bias];
      },
    };
    console.log('[dither] bayer + drifting threshold ready');
  }

  start();
})();
